名字: Online Chat Rooms

on:
  push:
    分支: [ "master" ]
  pull_request:
    分支: [ "master" ]
# 环境变量
env:
  # GitHub 用户名
  GH_USERNAME: SliverKeigo
  # commit 时使用的 Email
  GH_EMAIL: 1226355793@qq.com
  # 部署 GitHub Pages 的仓库，格式：用户名/仓库名
  GH_REPO: SliverKeigo/Online-Chat-Rooms
  # 部署 GitHub Pages 的仓库的分支名
  GH_BRANCH: master
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - 名字: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - 名字: Build
      run: |
        npm install
        npx webpack
    - 名字: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        # 指定前面准备的 token
        personal_token: ${{ secrets.Online_Chat_Rooms_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
        commit_message: ${{ github.event.head_commit.message }}
